### ISSUE TITLE
MakeProject时会异常

### ISSUE THREAD

**Issue by xuxingchen2018** [gdutxiaoxu/Router#1]
调用AS的build->Make Project时会有问题，提示assemble not found，把buildsrc目录删除，另外我把setting文件中的rootProject.name也注了，stub这个库是否可以删除呢，如果没有对应的注解配置，提示异常是否可行

**Comment by gdutxiaoxu** [comment]
我这边是可以正常编译的， buildsrc 主要是用来写 plugin 的

最新的代码已经吧 buildsrc 目录删除了，你 pull 一下试试
